apiVersion: v1
kind: Service
metadata:
  name: weather-domain-service
  labels: 
    app: weather-domain-service
    system: backend
spec:
  type: ClusterIP
  selector:
    app: weather-domain
    system: backend
  ports:
  - port: 9002
    targetPort: 9002
    protocol: TCP
 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-domain
  labels:
    app: weather-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: csimpleweb
          image: simpleweb
          imagePullPolicy: Never
          ports:
            - containerPort: 80
 ---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zerrademo-ingress
  labels: 
    app: zerrademo
    system: backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      host: api.my-shop.com
      paths:
      - path: /my-shop
        backend:
          serviceName: my-shop-backend
          servicePort: 80