#apiVersion: apps/v1
#kind: PersistentVolumeClaim
#metadata:
#  name: zerrademo-pets-mssql-volumeclaim
#  labels:
#    app: zerrademo-pets-mssql-volumeclaim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 256m
#
#---
#
#apiVersion: apps/v1
#kind: PersistentVolumeClaim
#metadata:
#  name: zerrademo-ledger1-mssql-volumeclaim
#  labels:
#    app: zerrademo-ledger1-mssql-volumeclaim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 256m
#
#---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-pets-postgresql-volumeclaim
  labels:
    app: zerrademo-pets-postgresql-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger1-postgresql-volumeclaim
  labels:
    app: zerrademo-ledger1-postgresql-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger1-eventstore-data-volumeclaim
  labels:
    app: zerrademo-ledger1-eventstore-data-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger1-eventstore-log-volumeclaim
  labels:
    app: zerrademo-ledger1-eventstore-log-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger2-eventstore-data-volumeclaim
  labels:
    app: zerrademo-ledger2-eventstore-data-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger2-eventstore-log-volumeclaim
  labels:
    app: zerrademo-ledger2-eventstore-log-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: zerrademo-petsdomain-mssql
#spec:
#  selector:
#    matchLabels:
#      app: zerrademo-petsdomain-mssql-pod
#  template:
#    metadata:
#      labels:
#        app: zerrademo-petsdomain-mssql-pod
#    spec:
#      terminationGracePeriodSeconds: 30
#      hostname: mssqlinst
#      containers:
#      - name: zerrademo-petsdomain-mssql-container
#        image: mcr.microsoft.com/mssql/server:2017-latest
#        ports:
#           - containerPort: 1433
#        env:
#          - name: MSSQL_PID
#            value: "Developer"
#          - name: ACCEPT_EULA
#            value: "Y"
#          - name: SA_PASSWORD
#            value: "Ld#dP22@uK4b"
#        volumeMounts:
#          - name: zerrademo-pets-mssql-volume
#            mountPath: /var/opt/mssql/data
#      volumes:
#        - name: zerrademo-pets-mssql-volume
#
#---
#
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: zerrademo-ledger1domain-mssql
#spec:
#  selector:
#    matchLabels:
#      app: zerrademo-ledger1domain-mssql-pod
#  template:
#    metadata:
#      labels:
#        app: zerrademo-ledger1domain-mssql-pod
#    spec:
#      terminationGracePeriodSeconds: 30
#      hostname: mssqlinst
#      containers:
#      - name: zerrademo-ledger1domain-mssql-container
#        image: mcr.microsoft.com/mssql/server:2017-latest
#        ports:
#           - containerPort: 1433
#        env:
#          - name: MSSQL_PID
#            value: "Developer"
#          - name: ACCEPT_EULA
#            value: "Y"
#          - name: SA_PASSWORD
#            value: "Ld#dP22@uK4b"
#        volumeMounts:
#          - name: zerrademo-ledger1-mssql-volume
#            mountPath: /var/opt/mssql/data
#      volumes:
#        - name: zerrademo-ledger1-mssql-volume
#
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-petsdomain-postgresql
spec:
  selector:
    matchLabels:
      app: zerrademo-petsdomain-postgresql-pod
  template:
    metadata:
      labels:
        app: zerrademo-petsdomain-postgresql-pod
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: zerrademo-petsdomain-postgresql-container
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "password123"
        volumeMounts:
          - name: zerrademo-pets-postgresql-volume
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: zerrademo-pets-postgresql-volume
          persistentVolumeClaim:
            claimName: zerrademo-pets-postgresql-volumeclaim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger1domain-postgresql
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger1domain-postgresql-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger1domain-postgresql-pod
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: zerrademo-ledger1domain-postgresql-container
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "password123"
        volumeMounts:
          - name: zerrademo-ledger1-postgresql-volume
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: zerrademo-ledger1-postgresql-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger1-postgresql-volumeclaim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger1domain-eventstore
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger1domain-eventstore-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger1domain-eventstore-pod
    spec:
      containers:
      - name: zerrademo-ledger1domain-eventstore-container
        image: eventstore/eventstore:latest
        ports:
           - containerPort: 1113
           - containerPort: 2113
        env:
          - name: EVENTSTORE_INSECURE
            value: "true"
          - name: EVENTSTORE_RUN_PROJECTIONS
            value: "All"
          - name: EVENTSTORE_EXT_TCP_PORT
            value: "1113"
          - name: EVENTSTORE_HTTP_PORT
            value: "2113"
        volumeMounts:
          - name: zerrademo-ledger1-eventstore-data-volume
            mountPath: /var/lib/eventstore
          - name: zerrademo-ledger1-eventstore-log-volume
            mountPath: /var/log/eventstore
      volumes:
        - name: zerrademo-ledger1-eventstore-data-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger1-eventstore-data-volumeclaim
        - name: zerrademo-ledger1-eventstore-log-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger1-eventstore-data-volumeclaim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger2domain-eventstore
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger2domain-eventstore-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger2domain-eventstore-pod
    spec:
      containers:
      - name: zerrademo-ledger2domain-eventstore-container
        image: eventstore/eventstore:latest
        ports:
           - containerPort: 1114
           - containerPort: 2114
        env:
          - name: EVENTSTORE_INSECURE
            value: "true"
          - name: EVENTSTORE_RUN_PROJECTIONS
            value: "All"
          - name: EVENTSTORE_EXT_TCP_PORT
            value: "1114"
          - name: EVENTSTORE_HTTP_PORT
            value: "2114"
        volumeMounts:
          - name: zerrademo-ledger2-eventstore-data-volume
            mountPath: /var/lib/eventstore
          - name: zerrademo-ledger2-eventstore-log-volume
            mountPath: /var/log/eventstore
      volumes:
        - name: zerrademo-ledger2-eventstore-data-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger2-eventstore-data-volumeclaim
        - name: zerrademo-ledger2-eventstore-log-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger2-eventstore-data-volumeclaim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-petsdomain
spec:
  selector:
    matchLabels:
      app: zerrademo-petsdomain-pod
  template:
    metadata:
      labels:
        app: zerrademo-petsdomain-pod
    spec:
      containers:
      - name: zerrademo-petsdomain-container
        image: szawaski/zerrademo-petsdomain:latest
        env:
          - name: ZerraDemo.Service.Weather
            value: "http://zerrademo-weatherdomain-service:9002"
#          - name: PetsSqlConnectionStringMSSQL
#            value: "Data Source=zerrademo-petsdomain-mssql-service,1401;Initial Catalog=ZerraDemoPets;User Id=sa;Password=Ld#dP22@uK4b;"
          - name: PetsSqlConnectionStringPOSTGRESQL
            value: "User ID=postgres;Password=password123;Host=zerrademo-petsdomain-postgresql-service;Port=1401;Database=zerrademopets;"
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-weatherdomain
spec:
  selector:
    matchLabels:
      app: zerrademo-weatherdomain-pod
  template:
    metadata:
      labels:
        app: zerrademo-weatherdomain-pod
    spec:
      containers:
      - name: zerrademo-weatherdomain-container
        image: szawaski/zerrademo-weatherdomain:latest
        env:
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger1domain
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger1domain-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger1domain-pod
    spec:
      containers:
      - name: zerrademo-ledger1domain-container
        image: szawaski/zerrademo-ledger1domain:latest
        env:
#         - name: Ledger1SqlConnectionStringMSSQL
#           value: "Data Source=zerrademo-ledger1domain-mssql-service,1402;Initial Catalog=ZerraDemoLedger;User Id=sa;Password=Ld#dP22@uK4b;"
          - name: Ledger1SqlConnectionStringPOSTGRESQL
            value: "User ID=postgres;Password=password123;Host=zerrademo-petsdomain-postgresql-service;Port=1402;Database=zerrademoledger;"
          - name: Ledger1EventStoreServer
            value: "tcp://zerrademo-ledger1domain-eventstore-service:2113"
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger2domain
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger2domain-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger2domain-pod
    spec:
      containers:
      - name: zerrademo-ledger2domain-container
        image: szawaski/zerrademo-ledger2domain:latest
        env:
          - name: Ledger2EventStoreServer
            value: "tcp://zerrademo-ledger2domain-eventstore-service:2114"
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-web
spec:
  selector:
    matchLabels:
      app: zerrademo-web-pod
  template:
    metadata:
      labels:
        app: zerrademo-web-pod
    spec:
      containers:
      - name: zerrademo-web-container
        image: szawaski/zerrademo-web:latest
        env:
          - name: ZerraDemo.Service.Pets
            value: "http://zerrademo-petsdomain-service:9001"
          - name: ZerraDemo.Service.Weather
            value: "http://zerrademo-weatherdomain-service:9002"
          - name: ZerraDemo.Service.Ledger1
            value: "http://zerrademo-ledger1domain-service:9003"
          - name: ZerraDemo.Service.Ledger2
            value: "http://zerrademo-ledger2domain-service:9004"
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger1domain-eventstore-service
spec:
  selector:
    app: zerrademo-ledger1domain-eventstore-pod
  ports:
  - port: 1113
    targetPort: 1113
    name: "tcp"
  - port: 2113
    targetPort: 2113
    name: "http"
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger2domain-eventstore-service
spec:
  selector:
    app: zerrademo-ledger2domain-eventstore-pod
  ports:
  - port: 1114
    targetPort: 1114
    name: "tcp"
  - port: 2114
    targetPort: 2114
    name: "http"
  type: NodePort
  
---

#apiVersion: v1
#kind: Service
#metadata:
#  name: zerrademo-petsdomain-mssql-service
#spec:
#  selector:
#    app: zerrademo-petsdomain-mssql-pod
#  ports:
#  - port: 1401
#    targetPort: 1433
#  type: NodePort
#  
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: zerrademo-ledger1domain-mssql-service
#spec:
#  selector:
#    app: zerrademo-ledger1domain-mssql-pod
#  ports:
#  - port: 1402
#    targetPort: 1433
#  type: NodePort
#  
#---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-petsdomain-postgresql-service
spec:
  selector:
    app: zerrademo-petsdomain-postgresql-pod
  ports:
  - port: 1401
    targetPort: 5432
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger1domain-postgresql-service
spec:
  selector:
    app: zerrademo-ledger1domain-postgresql-pod
  ports:
  - port: 1402
    targetPort: 5432
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-petsdomain-service
spec:
  selector:
    app: zerrademo-petsdomain-pod
  ports:
  - port: 9001
    targetPort: 5000
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-weatherdomain-service
spec:
  selector:
    app: zerrademo-weatherdomain-pod
  ports:
  - port: 9002
    targetPort: 5000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger1domain-service
spec:
  selector:
    app: zerrademo-ledger1domain-pod
  ports:
  - port: 9003
    targetPort: 5000
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger2domain-service
spec:
  selector:
    app: zerrademo-ledger2domain-pod
  ports:
  - port: 9004
    targetPort: 5000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-web-service
spec:
  selector:
    app: zerrademo-web-pod
  ports:
  - port: 9000
    targetPort: 80
    nodePort: 30000
  type: NodePort