version: "3.9"

services:

  zerrademo-petsdomain-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - MSSQL_PID=Developer
      - SA_PASSWORD=Ld#dP22@uK4b
      - ACCEPT_EULA=Y
    volumes:
      - zerrademo-pets-mssql-volume:/var/opt/mssql/data
    ports:
      - "1401:1433"
      
  zerrademo-ledger1domain-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - MSSQL_PID=Developer
      - SA_PASSWORD=Ld#dP22@uK4b
      - ACCEPT_EULA=Y
    volumes:
      - zerrademo-ledger1-mssql-volume:/var/opt/mssql/data
    ports:
      - "1402:1433"

  zerrademo-ledger1domain-eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
    volumes:
      - zerrademo-ledger1-eventstore_data-volume:/var/lib/eventstore
      - zerrademo-ledger1-eventstore_info-volume:/var/log/eventstore
    ports:
      - "1113:1113"
      - "2113:2113"
      
  zerrademo-ledger2domain-eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_EXT_TCP_PORT=1114
      - EVENTSTORE_HTTP_PORT=2114
    volumes:
      - zerrademo-ledger2-eventstore_data-volume:/var/lib/eventstore
      - zerrademo-ledger2-eventstore_info-volume:/var/log/eventstore
    ports:
      - "1114:1114"
      - "2114:2114"

  zerrademo-weatherdomain:
    image: zerrademo-weatherdomain
    environment:
      - ZerraDemo.Service.Pets=host.docker.internal:9001
      - ZerraDemo.Service.Weather=host.docker.internal:9002
      - ZerraDemo.Service.Ledger1=host.docker.internal:9003
      - ZerraDemo.Service.Ledger2=host.docker.internal:9004
      - PetsSqlConnectionString=Data Source=host.docker.internal,1401;Initial Catalog=ZerraDemoPets;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1SqlConnectionString=Data Source=host.docker.internal,1402;Initial Catalog=ZerraDemoLedger;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1EventStoreServer=tcp://host.docker.internal:2113
      - Ledger2EventStoreServer=tcp://host.docker.internal:2114
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/WeatherDomainDockerfile
    ports:
      - "9002:5000"
      
  zerrademo-petsdomain:
    image: zerrademo-petsdomain
    environment:
      - ZerraDemo.Service.Pets=host.docker.internal:9001
      - ZerraDemo.Service.Weather=host.docker.internal:9002
      - ZerraDemo.Service.Ledger1=host.docker.internal:9003
      - ZerraDemo.Service.Ledger2=host.docker.internal:9004
      - PetsSqlConnectionString=Data Source=host.docker.internal,1401;Initial Catalog=ZerraDemoPets;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1SqlConnectionString=Data Source=host.docker.internal,1402;Initial Catalog=ZerraDemoLedger;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1EventStoreServer=tcp://host.docker.internal:2113
      - Ledger2EventStoreServer=tcp://host.docker.internal:2114
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/PetsDomainDockerfile
    ports:
      - "9001:5000"
      
  zerrademo-ledger1domain:
    image: zerrademo-ledger1domain
    environment:
      - ZerraDemo.Service.Pets=host.docker.internal:9001
      - ZerraDemo.Service.Weather=host.docker.internal:9002
      - ZerraDemo.Service.Ledger1=host.docker.internal:9003
      - ZerraDemo.Service.Ledger2=host.docker.internal:9004
      - PetsSqlConnectionString=Data Source=host.docker.internal,1401;Initial Catalog=ZerraDemoPets;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1SqlConnectionString=Data Source=host.docker.internal,1402;Initial Catalog=ZerraDemoLedger;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1EventStoreServer=tcp://host.docker.internal:2113
      - Ledger2EventStoreServer=tcp://host.docker.internal:2114
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/Ledger1DomainDockerfile
    ports:
      - "9003:5000"
      
  zerrademo-ledger2domain:
    image: zerrademo-ledger2domain
    environment:
      - ZerraDemo.Service.Pets=host.docker.internal:9001
      - ZerraDemo.Service.Weather=host.docker.internal:9002
      - ZerraDemo.Service.Ledger1=host.docker.internal:9003
      - ZerraDemo.Service.Ledger2=host.docker.internal:9004
      - PetsSqlConnectionString=Data Source=host.docker.internal,1401;Initial Catalog=ZerraDemoPets;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1SqlConnectionString=Data Source=host.docker.internal,1402;Initial Catalog=ZerraDemoLedger;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1EventStoreServer=tcp://host.docker.internal:2113
      - Ledger2EventStoreServer=tcp://host.docker.internal:2114
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/Ledger2DomainDockerfile
    ports:
      - "9004:5000"
 
  zerrademo-webservice:
    image: zerrademo-web
    environment:
      - ZerraDemo.Service.Pets=host.docker.internal:9001
      - ZerraDemo.Service.Weather=host.docker.internal:9002
      - ZerraDemo.Service.Ledger1=host.docker.internal:9003
      - ZerraDemo.Service.Ledger2=host.docker.internal:9004
      - PetsSqlConnectionString=Data Source=host.docker.internal,1401;Initial Catalog=ZerraDemoPets;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1SqlConnectionString=Data Source=host.docker.internal,1402;Initial Catalog=ZerraDemoLedger;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1EventStoreServer=tcp://host.docker.internal:2113
      - Ledger2EventStoreServer=tcp://host.docker.internal:2114
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/WebDockerfile
    ports:
      - "9000:80"
      
volumes:
  zerrademo-pets-mssql-volume:
  zerrademo-ledger1-mssql-volume:
  zerrademo-ledger1-eventstore_data-volume:
  zerrademo-ledger1-eventstore_info-volume:
  zerrademo-ledger2-eventstore_data-volume:
  zerrademo-ledger2-eventstore_info-volume:
    