version: "3.9"

services:

  #zerrademo-petsdomain-mssql:
  #  image: mcr.microsoft.com/mssql/server:2017-latest
  #  environment:
  #    - MSSQL_PID=Developer
  #    - SA_PASSWORD=Ld#dP22@uK4b
  #    - ACCEPT_EULA=Y
  #  volumes:
  #    - zerrademo-pets-mssql-volume:/var/opt/mssql/data
  #  ports:
  #    - "1401:1433"
      
  #zerrademo-ledger1domain-mssql:
  #  image: mcr.microsoft.com/mssql/server:2017-latest
  #  environment:
  #    - MSSQL_PID=Developer
  #    - SA_PASSWORD=Ld#dP22@uK4b
  #    - ACCEPT_EULA=Y
  #  volumes:
  #    - zerrademo-ledger1-mssql-volume:/var/opt/mssql/data
  #  ports:
  #    - "1402:1433"

  zerrademo-petsdomain-postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - zerrademo-pets-postgresql-volume:/var/lib/postgresql/data
    ports:
      - 1401:5432
      
  zerrademo-ledger1domain-postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - zerrademo-ledger1-postgresql-volume:/var/lib/postgresql/data
    ports:
      - 1402:5432

  zerrademo-ledger1domain-eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
    volumes:
      - zerrademo-ledger1-eventstore-data-volume:/var/lib/eventstore
      - zerrademo-ledger1-eventstore-log-volume:/var/log/eventstore
    ports:
      - "1113:1113"
      - "2113:2113"
      
  zerrademo-ledger2domain-eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_EXT_TCP_PORT=1114
      - EVENTSTORE_HTTP_PORT=2114
    volumes:
      - zerrademo-ledger2-eventstore-data-volume:/var/lib/eventstore
      - zerrademo-ledger2-eventstore-log-volume:/var/log/eventstore
    ports:
      - "1114:1114"
      - "2114:2114"

  zerrademo-weatherdomain:
    image: szawaski/zerrademo-weatherdomain
    environment:
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/WeatherDomainDockerfile
    ports:
      - "9002:5000"
      
  zerrademo-petsdomain:
    image: szawaski/zerrademo-petsdomain
    environment:
      - ZerraDemo.Service.Weather=host.docker.internal:9002
      - PetsSqlConnectionStringMSSQL=Data Source=host.docker.internal,1401;Initial Catalog=ZerraDemoPets;User Id=sa;Password=Ld#dP22@uK4b;
      - PetsSqlConnectionStringPOSTGRESQL=User ID=postgres;Password=password123;Host=host.docker.internal;Port=1401;Database=zerrademopets;
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/PetsDomainDockerfile
    ports:
      - "9001:5000"
      
  zerrademo-ledger1domain:
    image: szawaski/zerrademo-ledger1domain
    environment:
      - Ledger1SqlConnectionStringMSSQL=Data Source=host.docker.internal,1402;Initial Catalog=ZerraDemoLedger;User Id=sa;Password=Ld#dP22@uK4b;
      - Ledger1SqlConnectionStringPOSTGRESQL=User ID=postgres;Password=password123;Host=host.docker.internal;Port=1402;Database=zerrademoledger;
      - Ledger1EventStoreServer=tcp://host.docker.internal:2113
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/Ledger1DomainDockerfile
    ports:
      - "9003:5000"
      
  zerrademo-ledger2domain:
    image: szawaski/zerrademo-ledger2domain
    environment:
      - Ledger2EventStoreServer=tcp://host.docker.internal:2114
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/Ledger2DomainDockerfile
    ports:
      - "9004:5000"
 
  zerrademo-webservice:
    image: szawaski/zerrademo-web
    environment:
      - ZerraDemo.Service.Pets=host.docker.internal:9001
      - ZerraDemo.Service.Weather=host.docker.internal:9002
      - ZerraDemo.Service.Ledger1=host.docker.internal:9003
      - ZerraDemo.Service.Ledger2=host.docker.internal:9004
      - LogFileDirectory=
    build:
      context: ../
      dockerfile: Deployment/WebDockerfile
    ports:
      - "9000:80"
      
volumes:
  #zerrademo-pets-mssql-volume:
  #zerrademo-ledger1-mssql-volume:
  zerrademo-pets-postgresql-volume:
  zerrademo-ledger1-postgresql-volume:
  zerrademo-ledger1-eventstore-data-volume:
  zerrademo-ledger1-eventstore-log-volume:
  zerrademo-ledger2-eventstore-data-volume:
  zerrademo-ledger2-eventstore-log-volume:  
    